import Head from "next/head";
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Home | Peworld</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./images/icon.svg"/>
            </Head>

            <main>
                <Link href="/jobs" className="d-flex justify-content-center">
                <button type="button" class="btn btn-primary">
                    Jobs List
                </button>
                </Link>
            </main>
        </div>
    );
}

// export async function getServerSideProps(context) {

//     const user = await axios.get("") 
//     return {
//       props: {}, // will be passed to the page component as props
//     }
//   }